version: '3.8'
services:
  db:
    image: mariadb:10.4.21
    command: --general-log=1 --general-log-file=/var/log/mysql/general-log.log --default-authentication-plugin=mysql_native_password
    volumes:
    - "./mysql:/var/lib/mysql"
    - "./mysql/mysql.log:/var/log/mysql/general-log.log"
    - "./samples/tables.sql:/root/tables.sql"
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
    - 3306:3306
  www:
    depends_on:
    - db
    command: docker-php-ext-install mysqli
    image: php:7.4.25-apache
    volumes:
    - ".:/var/www/html"
    ports:
    - 80:80
    - 443:443