version: '3.8'
services:
  db:
    image: mariadb:10.4.21
    volumes:
    - "./mysql:/var/lib/mysql"
    - "./mysql/mysql.log:/var/log/mysql/general-log.log"
    - "./tables.sql:/root/tables.sql"
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
    - 3306:3306
  www:
    depends_on:
    - db
    build: .
    volumes:
    - ".:/var/www/html"
    environment:
     PMA_HOST: db
    ports:
    - 8000:80
    - 443:443